### ISSUE TITLE
Updates to demos on slide 12 based on @Damo's feedback

### ISSUE THREAD

**Issue by Shavonna** [microsoft/aitour-advanced-coding-visual-studio-and-github-copilot#10]
Please update the slides and demos as explained in the feedback emails from @Damovisa.

Please follow up with me if you have any questions, and close this issue as soon as it's completed.

*Note, please prioritize the other 2 issues, which are blockers for this presentation to be presented. Please move on to this issue ONLY once those are completed and closed.

**Comment by elbruno** [comment]
Demos and slides updates with the feedback from @Damovisa 
Best!
